"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { FileState } from "../types/file";

const PREVIEW_CACHE = new Map<string, string>();
const MAX_CACHE_SIZE = 100; // Limit cache size to prevent memory issues

export function useLazyPreview(fileState: FileState) {
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const hasAutoGeneratedRef = useRef(false);

  const generatePreview = useCallback(() => {
    if (PREVIEW_CACHE.has(fileState.id)) {
      setPreviewUrl(PREVIEW_CACHE.get(fileState.id)!);
      return;
    }

    setIsLoading(true);
    try {
      const url = URL.createObjectURL(fileState.file);
      PREVIEW_CACHE.set(fileState.id, url);

      // Clean up old cache entries if we exceed the limit
      if (PREVIEW_CACHE.size > MAX_CACHE_SIZE) {
        const firstKey = PREVIEW_CACHE.keys().next().value;
        if (firstKey) {
          const firstUrl = PREVIEW_CACHE.get(firstKey);
          if (firstUrl) URL.revokeObjectURL(firstUrl);
          PREVIEW_CACHE.delete(firstKey);
        }
      }

      setPreviewUrl(url);
    } catch (error) {
      console.error("Failed to generate preview:", error);
    } finally {
      setIsLoading(false);
    }
  }, [fileState.id, fileState.file]);

  const cleanup = useCallback(() => {
    if (PREVIEW_CACHE.has(fileState.id)) {
      const url = PREVIEW_CACHE.get(fileState.id)!;
      URL.revokeObjectURL(url);
      PREVIEW_CACHE.delete(fileState.id);
    }
    setPreviewUrl(null);
  }, [fileState.id]);

  // Auto-generate preview for small files or when explicitly requested
  useEffect(() => {
    if (fileState.file.size < 1024 * 1024 && !hasAutoGeneratedRef.current && !previewUrl) { // Auto-generate for files < 1MB
      hasAutoGeneratedRef.current = true;
      generatePreview();
    }

    return cleanup;
  }, [fileState.file.size, generatePreview, cleanup, previewUrl]);

  return {
    previewUrl: previewUrl || fileState.previewUrl, // Fallback to existing URL
    isLoading,
    generatePreview,
    cleanup
  };
}

// Utility function to cleanup all previews
export function cleanupAllPreviews() {
  PREVIEW_CACHE.forEach(url => URL.revokeObjectURL(url));
  PREVIEW_CACHE.clear();
}